services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
